swagger:
 server-url: "https://banking-management.sanjayanbu.in"
spring:
  datasource:
    username: external_user
    url: jdbc:mysql://13.232.209.43:3306/banking_management
    password: 'M2l4OqMvc6PngsG@'