springdoc:
  api-docs:
    path: /api-docs
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/banking_management
    password: ''
  application:
    name: banking-management
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
   active: ${PROFILE:dev}